name: Deploying the Telegram bot on AWS

on:
  workflow_dispatch:
  
env:
  AWS_BUCKET_NAME: "terraform-state-for-telegram-bot-serverless"
  AWS_DYNAMO_DB_TABLE_NAME: "terraform-state-for-telegram-bot-serverless-locking"
  AWS_REGION: "us-east-1"
  TERRAFORM_PATH: "./terraform/"

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Replace Region in Provider section of Terraform
      with:
        aws-region: ${{ env.AWS_REGION }}     
      run: sed -i 's/us-east-1/eu-central-1/g' 00-provider.tf ; cat 00-provider.tf

    # - name: Terraform Init
    #   run: terraform -chdir=$TERRAFORM_PATH init

    # - name: Terraform Format
    #   run: terraform -chdir=$TERRAFORM_PATH fmt -check

    # - name: Terraform Plan
    #   run: terraform -chdir=$TERRAFORM_PATH plan -input=false
      
    # - name: Terraform Apply
    #   run: terraform -chdir=$TERRAFORM_PATH apply -auto-approve -input=false
