name: Destroy the Telegram bot

on:
  workflow_dispatch:
  
env:
  AWS_REGION: "us-west-2"
  TERRAFORM_PATH: "./terraform/"

permissions:
  contents: read

jobs:
  terraform:
    name: 'Destroy the bot'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Replace Region in Provider section of Terraform  
      run: sed -i 's/us-east-1/${{ env.AWS_REGION }}/g' $TERRAFORM_PATH/00-provider.tf ; cat $TERRAFORM_PATH/00-provider.tf

    - name: Terraform Init
      run: terraform -chdir=$TERRAFORM_PATH init
 
    - name: Terraform Apply
      run: terraform -chdir=$TERRAFORM_PATH apply -auto-approve -input=false -destroy
